name: transitway
description: Transport made easy.

publish_to: 'none'

version: 0.1.1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sign_in_button: ^3.2.0
  cached_network_image: ^3.1.0
  google_nav_bar: ^5.0.6
  dropdown_search: ^5.0.6
  google_maps_flutter: ^2.2.6
  geolocator: ^9.0.2
  http: ^0.13.6
  otp_text_field: ^1.1.3
  localstorage: ^4.0.0+1
  shared_preferences: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  provider: ^6.0.5
  syncfusion_flutter_barcodes: ^21.2.5
  flutter_webview_plugin: ^0.4.0
  flutter_polyline_points: ^1.0.0
  geocoding: ^2.1.0
  widgets_to_image: ^0.0.2
  overlayment: ^0.2.1
  permission_handler: ^10.2.0
  html: ^0.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: UberMoveMedium
      fonts:
        - asset: fonts/UberMoveMedium.otf
    - family: UberMoveBold
      fonts:
        - asset: fonts/UberMoveBold.otf
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
  assets:
    - assets/icons/logo.png
    - assets/Images/logotransp.png
    - assets/mapstyling.json
